/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Util;


/**
 *
 * @author frche1699
 */
public class PressureAltitude extends javax.swing.JFrame {

    // declaration
    SyncPress sp = new SyncPress();
    double press = 29.92;
    double pressAlt;
    double fieldElv = 0;

    /**
     * Creates new form PressureAltitude
     */
    public PressureAltitude() {
        initComponents();
        sp.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPress = new javax.swing.JLabel();
        lblPressSel = new javax.swing.JLabel();
        lblPressSelMetric = new javax.swing.JLabel();
        lblPressAlt = new javax.swing.JLabel();
        sldrFieldElv = new javax.swing.JSlider();
        lblFieldElv = new javax.swing.JLabel();
        sldrPress = new javax.swing.JSlider();
        lblFieldElvFeet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pressure Altitude");

        lblPress.setText("Altimeter Setting / QNH: ");

        lblPressSel.setText("29.92 inHg");

        lblPressSelMetric.setText("1013 hPa");

        lblPressAlt.setText("Pressure Altitude: 0 ft");

        sldrFieldElv.setMaximum(50);
        sldrFieldElv.setMinimum(-50);
        sldrFieldElv.setValue(0);
        sldrFieldElv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sldrFieldElvMouseReleased(evt);
            }
        });
        sldrFieldElv.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                sldrFieldElvCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        lblFieldElv.setText("Field Elevation: ");

        sldrPress.setMaximum(50);
        sldrPress.setMinimum(-50);
        sldrPress.setToolTipText("");
        sldrPress.setValue(0);
        sldrPress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sldrPressMouseReleased(evt);
            }
        });
        sldrPress.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                sldrPressCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        lblFieldElvFeet.setText("0 ft");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFieldElv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFieldElvFeet)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sldrPress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPressSel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPressSelMetric))
                                    .addComponent(lblPressAlt))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(sldrFieldElv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPress)
                    .addComponent(lblPressSel)
                    .addComponent(lblPressSelMetric))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldrPress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFieldElv)
                    .addComponent(lblFieldElvFeet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldrFieldElv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(lblPressAlt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldrPressCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_sldrPressCaretPositionChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_sldrPressCaretPositionChanged

    private void sldrFieldElvCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_sldrFieldElvCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sldrFieldElvCaretPositionChanged

    private void sldrFieldElvMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldrFieldElvMouseReleased
        // TODO add your handling code here:
        sldrFieldElv.setValue(0);
    }//GEN-LAST:event_sldrFieldElvMouseReleased

    private void sldrPressMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldrPressMouseReleased
        // TODO add your handling code here:
        sldrPress.setValue(0);
    }//GEN-LAST:event_sldrPressMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PressureAltitude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PressureAltitude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PressureAltitude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PressureAltitude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PressureAltitude().setVisible(true);
            }
        });
    }

    private class SyncPress extends Thread {

        @Override
        public void run() {
            while (true) {
                try {
                    fieldElv += Math.pow(sldrFieldElv.getValue() / 10.0, 3.0);
                    lblFieldElvFeet.setText(Formatting.dfNum0.format(fieldElv) + " ft");
                    press += sldrPress.getValue() / 1000.0;
                    lblPressSel.setText(Formatting.dfPressInHg.format(press) + " inHg");
                    lblPressSelMetric.setText(Formatting.dfPressHPa.format(press * 33.86) + " hPa");
                    //System.out.println(press);
                    pressAlt = 145366.45 * (1 - Math.pow(press / 29.92, 0.190284)) + fieldElv;
                    lblPressAlt.setText("Pressure Altitude: " + Formatting.dfNum0.format(pressAlt) + " ft");
                    Thread.sleep(50);
                } catch (InterruptedException ex) {
                    
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFieldElv;
    private javax.swing.JLabel lblFieldElvFeet;
    private javax.swing.JLabel lblPress;
    private javax.swing.JLabel lblPressAlt;
    private javax.swing.JLabel lblPressSel;
    private javax.swing.JLabel lblPressSelMetric;
    private javax.swing.JSlider sldrFieldElv;
    private javax.swing.JSlider sldrPress;
    // End of variables declaration//GEN-END:variables
}
