/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FTC;
import Util.*;
/**
 *
 * @author njche
 */
public class UtilLauncher extends javax.swing.JFrame {

    /**
     * Creates new form UtilLauncher
     */
    public UtilLauncher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTAStoGS = new javax.swing.JButton();
        btnFlightTime = new javax.swing.JButton();
        btnDensityAltitude = new javax.swing.JButton();
        btnPressAltitude = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Utilities");
        setType(java.awt.Window.Type.UTILITY);

        btnTAStoGS.setText("TAS to GS");
        btnTAStoGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTAStoGSActionPerformed(evt);
            }
        });

        btnFlightTime.setText("Flight Time");
        btnFlightTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightTimeActionPerformed(evt);
            }
        });

        btnDensityAltitude.setText("Density Altitude");
        btnDensityAltitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDensityAltitudeActionPerformed(evt);
            }
        });

        btnPressAltitude.setText("Pressure Altitude");
        btnPressAltitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPressAltitudeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTAStoGS, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(btnFlightTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(btnDensityAltitude, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(btnPressAltitude, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTAStoGS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFlightTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDensityAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPressAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTAStoGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTAStoGSActionPerformed
        // TODO add your handling code here:
        TAStoGS ttg = new TAStoGS();
        ttg.pack();
        ttg.setVisible(true);
    }//GEN-LAST:event_btnTAStoGSActionPerformed

    private void btnFlightTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightTimeActionPerformed
        // TODO add your handling code here:
        FlightTime ft = new FlightTime();
        ft.pack();
        ft.setVisible(true);
    }//GEN-LAST:event_btnFlightTimeActionPerformed

    private void btnDensityAltitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDensityAltitudeActionPerformed
        // TODO add your handling code here:
        DensityAltitude da = new DensityAltitude();
        da.pack();
        da.setVisible(true);
    }//GEN-LAST:event_btnDensityAltitudeActionPerformed

    private void btnPressAltitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPressAltitudeActionPerformed
        // TODO add your handling code here:
        PressureAltitude pa = new PressureAltitude();
        pa.pack();
        pa.setVisible(true);
    }//GEN-LAST:event_btnPressAltitudeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtilLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtilLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtilLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtilLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtilLauncher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDensityAltitude;
    private javax.swing.JButton btnFlightTime;
    private javax.swing.JButton btnPressAltitude;
    private javax.swing.JButton btnTAStoGS;
    // End of variables declaration//GEN-END:variables
}
